name: ci-cd

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Build up system
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install requirements
        run: |
          python -m pip install pip --upgrade
          pip install -r requirements.txt

      - name: Linting code
        run: flake8 .

      - name: Testing
        run: python manage.py test